version: '3'
services:
  my-app:
    image: node-app:1.0
    ports:
     - 3000:3000
    environment:
     - MONGO_DB_USERNAME=admin
     - MONGO_DB_PWD=pwd
  mongodb:
    image: mongo
    restart: always
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=pwd
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=pwd
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"
